#!/usr/bin/env bash

######################################################################
# Complete install:
# Install all dependencies for Torch7, then Torch7 itself.
######################################################################

# Install dependencies
curl -s https://raw.github.com/clementfarabet/torchinstall/master/install-deps | bash

# Default path
export PREFIX=/usr/local

# Install Torch7
curl -s https://raw.github.com/clementfarabet/torchinstall/master/install-torch | bash
