#!/usr/bin/env bash

######################################################################
# This script installs required dependencies for Torch7
######################################################################

# Based on Platform:
if [[ `uname` == 'Darwin' ]]; then
    # GCC?
    if [[ `which gcc` == '' ]]; then
        echo "MacOS doesn't come with GCC: please install XCode and the command line tools."
        exit
    fi

    # Install Homebrew (pkg manager):
    if [[ `which brew` == '' ]]; then
        ruby -e "$(curl -fsSL https://raw.github.com/mxcl/homebrew/go/install)"
    fi

    # Install dependencies:
    brew install git readline cmake wget qt
    brew install libjpeg imagemagick zeromq 
    brew link readline --force
    brew remove gnuplot
    brew install gnuplot --wx --cairo --pdf --with-x

elif [[ `uname` == 'Linux' ]]; then
    # Aptitude?
    if [[ `which apt-get` == '' ]]; then
        echo '==> apt-get not found, platform not supported'
        exit
    fi

    # Install dependencies for Torch:
    sudo apt-get install -y python-software-properties
    sudo add-apt-repository ppa:chris-lea/zeromq
    sudo add-apt-repository ppa:chris-lea/node.js
    sudo apt-get update
    sudo apt-get install -y build-essential
    sudo apt-get install -y gcc g++
    sudo apt-get install -y cmake
    sudo apt-get install -y curl
    sudo apt-get install -y libreadline-dev
    sudo apt-get install -y git-core
    sudo apt-get install -y libqt4-core libqt4-gui libqt4-dev
    sudo apt-get install -y libjpeg-dev
    sudo apt-get install -y libpng-dev
    sudo apt-get install -y ncurses-dev
    sudo apt-get install -y imagemagick
    sudo apt-get install -y libzmq-dev
    sudo apt-get install -y gfortran
    sudo apt-get install -y unzip
    sudo apt-get install -y gnuplot
    sudo apt-get install -y gnuplot-x11
    sudo add-apt-repository ppa:chris-lea/zeromq
    sudo apt-get update

    # Get and build OpenBlas (Torch is much better with a decent Blas)
    cd /tmp/
    git clone http://github.com/xianyi/OpenBLAS.git
    cd OpenBLAS
    make NO_AFFINITY=1 USE_OPENMP=1
    sudo make install

else
    # Unsupported
    echo '==> platform not supported, aborting'
    exit
fi

# Done.
echo "==> Torch7's dependencies have been installed"
