#!/usr/bin/env bash

######################################################################
# Torch install
#
# This script installs Torch7, and a few extra packages
# (penlight, optim, parallel, image).
# 
# The install is done via Luarocks, which enables package
# versions. This is the recommended method to deploy Torch,
# torch-pkg is being deprecated.
#
#    Once this script has been run once, you should be able to run
#    extra luarocks commands, and in particular install new packages:
#    $ luarocks install json
#    $ torch
#    > require 'json'
#
######################################################################

# Prefix:
PREFIX=${PREFIX-/usr/local}
echo "Installing Torch into: $PREFIX"

if [[ `uname` == 'Linux' ]]; then
    export CMAKE_LIBRARY_PATH=/opt/OpenBLAS/include:/opt/OpenBLAS/lib:$CMAKE_LIBRARY_PATH
fi

# Build and install Torch7
cd /tmp
git clone https://github.com/torch/luajit-rocks.git
cd luajit-rocks
mkdir build; cd build
git checkout master; git pull
rm -f CMakeCache.txt
cmake .. -DCMAKE_INSTALL_PREFIX=$PREFIX -DCMAKE_BUILD_TYPE=Release
RET=$?; if [ $RET -ne 0 ]; then echo "Error. Exiting."; exit $RET; fi
make
RET=$?; if [ $RET -ne 0 ]; then echo "Error. Exiting."; exit $RET; fi
make install || sudo -E make install
RET=$?; if [ $RET -ne 0 ]; then echo "Error. Exiting."; exit $RET; fi
# check if we are on mac and fix RPATH for local install
path_to_install_name_tool=$(which install_name_tool)
if [ -x "$path_to_install_name_tool" ] 
then
   install_name_tool -id ${PREFIX}/lib/libluajit.dylib ${PREFIX}/lib/libluajit.dylib
fi

# Statuses:
sundown=ok
cwrap=ok
paths=ok
torch=ok
nn=ok
dok=ok
gnuplot=ok
qtlua=ok
qttorch=ok
lfs=ok
penlight=ok
sys=ok
xlua=ok
image=ok
optim=ok
cjson=ok
trepl=ok

path_to_nvcc="$(which nvcc)"
if [[ -x "$path_to_nvcc" ]]; then  
    cutorch=ok
    cunn=ok
fi

function EXIT_ON_FAIL(){
    "$@"
    RET=$?
    if [[ $RET -ne 0 ]]; then
        echo "Error encountered when attempting to perform:" >&2
        echo "--> $* . Exiting." >&2
        exit $RET
    fi
}

function DO_OR_SUDO(){
    "$@" || sudo -E "$@"
}

# Install base packages:
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install sundown
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install cwrap
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install paths
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install torch
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install nn
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install dok
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install gnuplot

if [[ -n "$cutorch" ]]; then
    DO_OR_SUDO $PREFIX/bin/luarocks install cutorch  || cutorch=failed
fi

if [[ -n "$cunn" ]]; then
    DO_OR_SUDO $PREFIX/bin/luarocks install cunn  || cunn=failed
fi

EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install qtlua
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install qttorch
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install luafilesystem
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install penlight
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install sys
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install xlua
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install image
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install optim
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install lua-cjson
EXIT_ON_FAIL DO_OR_SUDO $PREFIX/bin/luarocks install trepl

# Done.
echo ""
echo "=> Torch7 has been installed successfully"
echo ""
echo "  + Extra packages have been installed as well:"
echo "     $ luarocks list"
echo ""
echo "  + To install more packages, do:"
echo "     $ luarocks search --all"
echo "     $ luarocks install PKG_NAME"
echo ""
echo "  + Note: on MacOS, it's a good idea to install GCC 5 to enable OpenMP."
echo "     You can do this by with brew"
echo "      $ brew install gcc --without-multilib"
echo "     type the following lines before running the installation script"
echo "      export CC=gcc-5"
echo "      export CXX=g++-5"
echo "     For installing cunn, you will need instead the default AppleClang compiler,"
echo "     which means you should open a new terminal (with unexported CC and CXX) and"
echo "      luarocks install cunn"
echo ""
echo "  + packages installed:"
echo "    - sundown   : " $sundown
echo "    - cwrap     : " $cwrap
echo "    - paths     : " $paths
echo "    - torch     : " $torch
echo "    - nn        : " $nn
echo "    - dok       : " $dok
echo "    - gnuplot   : " $gnuplot
[ -n "$cutorch" ] && echo "    - cutorch   : " $cutorch
[ -n "$cunn" ]    && echo "    - cunn      : " $cunn
echo "    - qtlua     : " $qtlua
echo "    - qttorch   : " $qttorch
echo "    - lfs       : " $lfs
echo "    - penlight  : " $penlight
echo "    - sys       : " $sys
echo "    - xlua      : " $xlua
echo "    - image     : " $image
echo "    - optim     : " $optim
echo "    - cjson     : " $cjson
echo "    - trepl     : " $trepl
echo ""
