#!/usr/bin/env bash

######################################################################
# Torch install
#
# This script installs Torch7, and a few extra packages
# (penlight, optim, parallel, image).
# 
# WARNING: This install doesn't install any dependency, and assumes
# that these are all met... Please see install, for full deps install.
# 
# The install is done via Luarocks, which enables package
# versions. This is the recommended method to deploy Torch,
# torch-pkg is being deprecated.
#
#    Once this script has been run once, you should be able to run
#    extra torch-rocks commands, and in particular install new packages:
#    $ torch-rocks install json
#    $ torch
#    > require 'json'
#
######################################################################

# Prefix:
PREFIX=$HOME/local
echo "Installing Torch into: $PREFIX"

# Build and install Torch7
cd /tmp
git clone https://github.com/andresy/torch
cd torch
mkdir build; cd build
cmake .. -DWITH_ROCKS=1 -DCMAKE_INSTALL_PREFIX=$PREFIX
make

# Install Torch7, with LuaJIT support, and extra packages
$PREFIX/bin/torch-rocks install penlight
$PREFIX/bin/torch-rocks install image
$PREFIX/bin/torch-rocks install parallel
$PREFIX/bin/torch-rocks install optim
$PREFIX/bin/torch-rocks install json

# Done.
echo "==> Torch7 has been installed successfully"
echo "  + Extra packages [penlight, image, parallel, optim, json] have been installed as well:"
echo "     $ torch-rocks list"
echo ""
echo "  + To install more packages, do:"
echo "     $ torch-rocks search --all"
echo "     $ torch-rocks install PKG_NAME"
echo ""
echo "  + Note: on MacOS, it's a good idea to install GCC 4.6 to enable OpenMP."
echo "          You can do this by installing the GFortran bundles provided here:"
echo "          http://gcc.gnu.org/wiki/GFortranBinaries"

