#!/usr/bin/env bash

# Based on Platform:
if [[ `uname` == 'Darwin' ]]; then
    # GCC?
    if [[ `which gcc` == '' ]]; then
        echo "MacOS doesn't come with GCC: please install XCode and the command line tools."
        exit
    fi

    # Install Homebrew (pkg manager):
    if [[ `which brew` == '' ]]; then
        ruby <(curl -fsSkL raw.github.com/mxcl/homebrew/go)
    fi

    # Install dependencies:
    brew install git readline cmake wget qt
    brew install libjpeg imagemagick zeromq nodejs

    # Install NPM
    if [[ `which npm` == '' ]]; then
        curl https://npmjs.org/install.sh | sh
    fi

    # Install Node.js packages
    npm install express@2.x ejs stripcolorcodes

    # Install Torch7
    mkdir -p ~/.torch/torch-pkg; cd ~/.torch/torch-pkg
    git clone https://github.com/andresy/torch
    mkdir -p torch/build; cd torch/build
    git pull
    rm -f CMakeCache.txt
    cmake .. -DWITH_LUA_JIT=1
    make install

    # Install extra Torch packages:
    torch-pkg -local install image parallel webterm nnx

    # Done.
    echo "==> Torch7 has been installed successfully"
    echo "  + Extra packages [image, parallel, webterm, nnx] have been installed locally"
    echo "  + To install more packages, do:"
    echo "    $ torch-pkg list"
    echo "    $ torch-pkg -local install json"

elif [[ `uname` == 'Linux' ]]; then
    # Aptitude?
    if [[ `which apt-get` == '' ]]; then
        echo '==> apt-get not found, platform not supported'
        exit
    fi

    # Install dependencies for Torch:
    sudo add-apt-repository ppa:chris-lea/zeromq
    sudo apt-get update
    sudo apt-get install -y build-essential gcc g++ cmake libreadline-dev git-core
    sudo apt-get install -y libqt4-core libqt4-gui libqt4-dev
    sudo apt-get install -y libjpeg-dev imagemagick nodejs npm
    sudo apt-get install -y libzmq-dev

    # Install Node.js packages
    npm install express@2.x ejs stripcolorcodes

    # Install Torch:
    mkdir -p ~/.torch/torch-pkg; cd ~/.torch/torch-pkg
    git clone https://github.com/andresy/torch
    mkdir -p torch/build; cd torch/build
    git pull
    rm -f CMakeCache.txt
    cmake .. -DWITH_LUA_JIT=1
    make
    sudo make install

    # Install extra Torch packages:
    torch-pkg -local install image parallel webterm nnx

    # Done.
    echo "==> Torch7 has been installed successfully"
    echo "  + Extra packages [image, parallel, webterm, nnx] have been installed locally"
    echo "  + To install more packages, do:"
    echo "    $ torch-pkg list"
    echo "    $ torch-pkg -local install json"

else
    # Unsupported
    echo '==> platform not supported, aborting'
fi
